# Generated by Django 3.2.2 on 2021-05-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='superadmin',
            name='username',
            field=models.CharField(default='superadmin', max_length=255),
        ),
    ]
